import { Inter } from 'next/font/google'
import './globals.css'
import Heading from './components/Heading'
import Navbar from './components/Navbar'
import { Footer } from './Footer'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'ACME',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Heading/>
        {children}
       <Footer/>
        <Navbar/>
        </body>
    </html>
  )
}
